name: laundary_system
description: A new Flutter Final Year Project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.3.0
  google_fonts: ^3.0.1
  flutter_native_splash: ^2.2.16
  flutter_bloc: ^8.1.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  provide: ^1.0.2
  shimmer: ^2.0.0
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.3
  location: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter_native_splash:
  color: "#ffffff"
  android_12:
  image: assets/app_Icon.png

flutter:

  uses-material-design: true

  assets:
    - assets/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
